[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  ignore = "test -d embed && echo 'Ignoring /embed' || exit 0"
